export type RadarSetup = {
  setup_id: string;
  symbol: string;
  direction: string;
  status?: string;
  strategy_profile?: string;
  profile_variant_name?: string;
  inherited_base_profile?: string;
  timeframe_profile?: string | null;
  selected_tp_model?: string | null;
  expansion_min?: string | number;
  expansion_max?: string | number;
  retracement_window?: string | number;
  entry_model?: string;
  current_state: string;
  progress_percent: number;
  setup_percentage?: number;
  missing_requirements: string[];
  invalidation_reason: string | null;
  time_remaining: string | null;
  created_at?: string | null;
  updated_at?: string | null;
  invalidated_at?: string | null;
  entry_price?: string | null;
  swing_16m_id?: string | null;
  expansion_16m_id?: string | null;
  fvg_16m_id?: string | null;
  fvg_12m_id?: string | null;
  fvg_8m_id?: string | null;
  watched_timeframes?: string[];
  latest_relevant_price?: string;
  stop_reference: string | null;
  target_reference: string | null;
  higher_timeframe_context_status?: string | null;
  fvg_16m_status?: string | null;
  expansion_ratio?: string | number | null;
  fvg_12m_status?: string | null;
  eight_minute_candle_count_after_16m_fvg?: string | number | null;
  retracement_within_3_8m_candles?: boolean | null;
  first_candle_entered_12m_fvg?: boolean | null;
  entry_candle_boundary_respected?: boolean | null;
  entry_ready?: boolean;
  one_trade_per_fvg_status?: string | null;
  rejection_reason?: string | null;
  source?: string | null;
};
